parameters:
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    WSIIA\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    WSIIA\Command\PostLineCommand:
        - "%env(resolve:SLACK_URL)%"
